apiVersion: v2
name: dex-app
version: "2.2.0"
appVersion: "2.2.0"
description: OpenID Connect (OIDC) identity and OAuth 2.0 provider with pluggable connectors
keywords:
  - authentication
  - oidc
icon: https://s.giantswarm.io/app-icons/dex/2/icon_light.svg
home: https://github.com/giantswarm/dex-app
sources:
  - https://github.com/dexidp/dex/
  - https://github.com/mintel/dex-k8s-authenticator
maintainers:
  - name: kfox1111
    email: Kevin.Fox@pnnl.gov
  - name: sstarcher
    email: shane.starcher@gmail.com
  - name: rendhalver
    email: pete.brown@powerhrg.com
  - name: vi7
    email: vi7alya@gmail.com
  - name: Aaron Roydhouse
    email: aaron@roydhouse.com
  - name: Nick Badger
    email: nbadger@mintel.com
annotations:
  application.giantswarm.io/team: shield
  application.giantswarm.io/readme: https://raw.githubusercontent.com/giantswarm/dex-app/v[[ .Version ]]/README.md
  application.giantswarm.io/values-schema: https://raw.githubusercontent.com/giantswarm/dex-app/v[[ .Version ]]/helm/dex-app/values.schema.json
  config.giantswarm.io/version: 1.x.x
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
dependencies:
  - name: dex
    version: "0.23.0"
