annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Use tpl for dynamic image values and add digest support"
  artifacthub.io/images: |
    - name: dex
      image: ghcr.io/dexidp/dex:v2.42.0
apiVersion: v2
appVersion: 4a81bce18d5dcac35489cd95ebc363314
description: OpenID Connect (OIDC) identity and OAuth 2.0 provider with pluggable
  connectors.
home: https://dexidp.io/
icon: https://dexidp.io/favicon.png
keywords:
- oidc
- oauth
- identity-provider
- saml
kubeVersion: '>=1.14.0-0'
maintainers:
- email: mark.sagikazar@gmail.com
  name: sagikazarmark
  url: https://sagikazarmark.com
name: dex
sources:
- https://github.com/dexidp/dex
- https://github.com/dexidp/helm-charts/tree/master/charts/dex
type: application
version: 0.23.0
